marks = []
f1 = input("Enter name : ")
marks.append(f1)
f2 = input("Enter name : ")
marks.append(f2)
f3 = input("Enter n ame : ")
marks.append(f3)
f4 = input("Enter name : ")
marks.append(f4)
f5 = input("Enter name : ")
marks.append(f5)
f6 = input("Enter name : ")
marks.append(f6)
print(marks)