a = set()
num1 = input("enter the number :")
a.add(num1)
num2 = input("enter the number :")
a.add(num2)
num3 = input("enter the number :")
a.add(num3)
num4 = input("enter the number :")
a.add(num4)
num5 = input("enter the number :")
a.add(num5)
num6 = input("enter the number :")
a.add(num6)
num7 = input("enter the number :")
a.add(num7)
num8 = input("enter the number :")
a.add(num8)

print(a)